# Generated by Django 3.0.8 on 2020-07-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Shakaib Hassan', max_length=50)),
                ('email', models.CharField(default='shakaibhassan16@gmail.com', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainApplication.Writers'),
            preserve_default=False,
        ),
    ]
