# Generated by Django 3.0.8 on 2020-07-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0003_remove_articles_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writers',
        ),
    ]
