# Generated by Django 3.0.8 on 2020-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0004_delete_writers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Shakaib Hassan', max_length=50)),
                ('email', models.CharField(default='shakaibhassan16@gmail.com', max_length=50)),
            ],
        ),
    ]
