# Generated by Django 3.0.8 on 2020-07-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0005_writers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writers',
            new_name='Author',
        ),
    ]
