# Generated by Django 3.0.8 on 2020-07-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0006_auto_20200723_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
