# Generated by Django 3.0.8 on 2020-07-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApplication', '0007_auto_20200723_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Shakaib Hassan', max_length=50)),
                ('email', models.CharField(default='shakaibhassan16@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.TextField()),
                ('published_date', models.DateField()),
                ('time_read', models.CharField(choices=[('5', '5 min'), ('10', '10 min'), ('15', '15 min'), ('20', '20 min'), ('25', '25 min')], max_length=10)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApplication.Author')),
            ],
        ),
    ]
